### ISSUE TITLE
Update Storage-Docu

### ISSUE THREAD

**Issue by chrklemm** [chrklemm/SESMG#22]
With the introduction of version SESMG v0.0.4, the fields "input/capacity ratio (invest)" and "output/capacity ratio (invest)" replace the fields input and output capacity. This has not yet been included in the documentation.

**Comment by janik257** [comment]
The text and image has been changed. The description of "Non-Convex Investment" and "Fix Investment Costs /(Cu/A) is missing

**Comment by chrklemm** [comment]
"input/capacity   ratio (invest)" and "output/capacity   ratio (invest)" are missing as well
