### ISSUE TITLE
Variable Costs of Transformers with two outputs 

### ISSUE THREAD

**Issue by GregorBecker** [chrklemm/SESMG#3]
Variable Costs of Transformers with two outputs are not considered correctly. Only the costs of output 1 is used to calculate the "total variable costs". However, as the "Total System Costs" are calculated in a different way, this value is calculated correctly!!

**Comment by chrklemm** [comment]
check also input and outputs in interactive results

**Comment by chrklemm** [comment]
done @GregorBecker ?
