### ISSUE TITLE
Add Constraints

### ISSUE THREAD

**Issue by chrklemm** [chrklemm/SESMG#33]
https://oemof-solph.readthedocs.io/en/latest/usage.html?highlight=response#sinkdsm-custom

**Comment by chrklemm** [comment]
Finished, right @janik257 and @GregorBecker ?

**Comment by GregorBecker** [comment]
@chrklemm The implementation of the area competition is still pending.

**Comment by GregorBecker** [comment]
Done in Branch v0.2 @chrklemm #63
