### ISSUE TITLE
result output

### ISSUE THREAD

**Issue by FredericH94** [chrklemm/SESMG#38]
Bei der Ergebnisausgabe ist mir aufgefallen, dass der "Input" und "Output" der Transformer vertauscht ist. Die Werte sind meiner Ansicht nach richtig und lediglich in den falschen Spalten.
Bei den anderen Komponenten (z.B. Storages) ist es meiner Ansicht nacht richtig.

**Comment by chrklemm** [comment]
Thanks for your feedback! Yesterday @GregorBecker and I looked at the appropriate places in the code. The errors will be fixed with the upcoming update to version v0.1.0.

**Comment by chrklemm** [comment]
done @GregorBecker ?
