### ISSUE TITLE
Add non-convex investments

### ISSUE THREAD

**Issue by GregorBecker** [chrklemm/SESMG#7]
Non-convex investments are possible with oemof 0.4.0: https://forum.openmod-initiative.org/t/oemof-problem-investment-decision/1903/10

**Comment by chrklemm** [comment]
- [ ] Non-Convex Sources

- [ ] Non-Convex Generic Transformers

- [ ] Non-Convex Heat-Pumps

- [ ] Non-Convex Storages

- [ ] Non-Convex directed Links

- [ ] Non-Convex undirected Links

- [ ] Add Offset Costs to Result outputs

- [ ] Update Example-Scenario Spreadsheet

**Comment by chrklemm** [comment]
See: #25
